---
title: "Project 1 Report"
author: "Savannah Sauers, Lera Martinez, Simon Tao"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
### Read in packages, data, and clean data for project analysis
library(tidyverse)
```

```{r, include=FALSE}
project <- read.csv("~/Desktop/Fall 2026/DATS6101/DATS6101_Project_MTA_Subway_Hourly_Ridership.csv")
```

```{r, include=FALSE}
# Make sure columns are cast to correct types
project$borough <- as.factor(project$borough)
project$payment_method <- as.factor(project$payment_method)
project$fare_class_category <- as.factor(project$fare_class_category)
project$ridership <- as.numeric(project$ridership)
project$transfers <- as.numeric(project$transfers)
```

```{r, include=FALSE}
# Add 24-hour time column
project <- project %>%
  mutate(
    timestamp = mdy_hms(transit_timestamp),
    hour = hour(timestamp)
  )
```

```{r, include=FALSE}
# Add categories for morning, afternoon, evening, night
# Morning (5am - noon), afternoon (noon - 4pm), evening (4pm - 8pm), night (8pm - 5am)
project <- project %>%
  mutate(
    time_of_day = case_when(
      hour >= 5 & hour < 11 ~ "Morning",
      hour >= 11 & hour < 16 ~ "Mid Day",
      hour >= 16 & hour < 21 ~ "Evening",
      TRUE ~ "Night"
    )
  )
```

```{r, include=FALSE}
# Add day of week column
project <- project %>%
  mutate(
    day_of_week = wday(timestamp, label = TRUE)
  )
```

# Introduction

# Data Description

# EDA

# Analysis

# Conclusions